name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # 3. Build and push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iaiperi04772/actions:latest
      
      # 4: Настройка Ansible и запуск Playbook
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          inventory: |
            [web_servers]
            ${{ secrets.SERVER_IP }} ansible_user=${{ secrets.ANSIBLE_USER }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}