name: Build and Push Docker Image

# Запускать workflow при пуше в определённые ветки или при создании релиза
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Сборка Docker-образа
      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker build -t ${{ secrets.DOCKER_USERNAME }}/actions:${{ github.sha }} ../../Dockerfile
          docker tag ${{ secrets.DOCKER_USERNAME }}/actions:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/actions:latest ../../Dockerfile

      # 4. Публикация Docker-образа в Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/actions:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/actions:latest