name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iaiperi04772/actions:latest

            # # 3. Проверка версии Docker
      # - name: Check Docker version
      #   run: docker --version

      # # 4. Дебаг Docker Buildx
      # - name: Debug Docker Buildx
      #   run: |
      #     docker buildx ls
      #     docker buildx inspect

      # # 5. Сборка Docker-образа
      # - name: Build Docker Image
      #   run: |
      #     docker buildx create --use  # Создаём и выбираем контекст сборки
      #     docker buildx build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/actions:${{ github.sha }} -f Dockerfile .
      #     docker buildx build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/actions:latest -f Dockerfile .

      # # 6. Публикация Docker-образа в Docker Hub
      # - name: Push Docker Image
      #   run: |
      #     docker push ${{ secrets.DOCKER_USERNAME }}/actions:${{ github.sha }}
      #     docker push ${{ secrets.DOCKER_USERNAME }}/actions:latest
